##name: Run PopSol -> Sheets hourly

##on:
  schedule:
    # Roda 10 minutos antes da hora cheia, das 11:50h às 23:50h UTC.
    # No fuso America/Sao_Paulo (fuso-3), isso equivale às 08:50h às 20:50h.
    # Se você quiser das 08:50h às 20:50h (SP), o intervalo UTC está correto (11-23)
    - cron: "50 11-23 * * *" 
  workflow_dispatch: {}    # permite rodar manualmente

# Evitar sobreposição de jobs
##concurrency:
  group: pops_to_sheets
  cancel-in-progress: true

##jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
    
# Eu uso o fuso horário só para os logs; o agendamento (CRON) é sempre em UTC.
# Por isso deixo 11–23, que corresponde a rodar das 08h às 20h no horário de Brasília (UTC−3).

      TZ: America/Sao_Paulo
      # Função de secrets
      POPSOL_USER: ${{ secrets.POPSOL_USER }}
      POPSOL_PASS: ${{ secrets.POPSOL_PASS }}
      APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script (headless)
        run: |
          python "Bot pix pagamentos.py"


    # Código feito por Raphael Barbosa, não permitida a republicação da mesma dentro de qualquer sistema repositório fechado.
